INSERT INTO group_table (`group_name`, `group_rule`) VALUES ('공학스터디', '모든권한');
INSERT INTO group_table (`group_name`, `group_rule`) VALUES ('의학스터디', '읽기/쓰기 권한');
INSERT INTO group_table (`group_name`, `group_rule`) VALUES ('독서스터디', '읽기권한');
INSERT INTO group_table (`group_name`, `group_rule`) VALUES ('공학스터디', '모든권한');
INSERT INTO group_table (`group_name`, `group_rule`) VALUES ('의학스터디', '읽기/쓰기 권한');
INSERT INTO group_table (`group_name`, `group_rule`) VALUES ('독서스터디', '읽기권한');
INSERT INTO group_table (`group_name`, `group_rule`) VALUES ('공학스터디', '모든권한');
INSERT INTO group_table (`group_name`, `group_rule`) VALUES ('의학스터디', '읽기/쓰기 권한');
INSERT INTO group_table (`group_name`, `group_rule`) VALUES ('독서스터디', '읽기권한');
INSERT INTO group_table (`group_name`, `group_rule`) VALUES ('공학스터디', '모든권한');
INSERT INTO group_table (`group_name`, `group_rule`) VALUES ('의학스터디', '읽기/쓰기 권한');
INSERT INTO group_table (`group_name`, `group_rule`) VALUES ('독서스터디', '읽기권한');
INSERT INTO group_table (`group_name`, `group_rule`) VALUES ('공학스터디', '모든권한');
INSERT INTO group_table (`group_name`, `group_rule`) VALUES ('의학스터디', '읽기/쓰기 권한');
INSERT INTO group_table (`group_name`, `group_rule`) VALUES ('독서스터디', '읽기권한');
INSERT INTO group_table (`group_name`, `group_rule`) VALUES ('공학스터디', '모든권한');
INSERT INTO group_table (`group_name`, `group_rule`) VALUES ('의학스터디', '읽기/쓰기 권한');
INSERT INTO group_table (`group_name`, `group_rule`) VALUES ('독서스터디', '읽기권한');
INSERT INTO group_table (`group_name`, `group_rule`) VALUES ('공학스터디', '모든권한');
INSERT INTO group_table (`group_name`, `group_rule`) VALUES ('의학스터디', '읽기/쓰기 권한');
INSERT INTO group_table (`group_name`, `group_rule`) VALUES ('독서스터디', '읽기권한');
INSERT INTO group_table (`group_name`, `group_rule`) VALUES ('공학스터디', '모든권한');
INSERT INTO group_table (`group_name`, `group_rule`) VALUES ('의학스터디', '읽기/쓰기 권한');
INSERT INTO group_table (`group_name`, `group_rule`) VALUES ('독서스터디', '읽기권한');
INSERT INTO group_table (`group_name`, `group_rule`) VALUES ('공학스터디', '모든권한');
INSERT INTO group_table (`group_name`, `group_rule`) VALUES ('의학스터디', '읽기/쓰기 권한');
INSERT INTO group_table (`group_name`, `group_rule`) VALUES ('독서스터디', '읽기권한');